function required(id){
	if($.trim($(id).val())!=""){
		return true;}
	else {
		return false;}
	}
	function table() {
	document.getElementById("age").innerHTML=document.getElementById("age_en").value ;
	document.getElementById("education").innerHTML=document.getElementById("education_en").value ;
	document.getElementById("job").innerHTML=document.getElementById("job_en").value ;
	document.getElementById("hobby").innerHTML=document.getElementById("hobby_en").value ;
	document.getElementById("tol").innerHTML=document.getElementById("tol_en").value ;
	document.getElementById("part2fb").innerHTML=document.getElementById("part2fb_en").value ;
	document.getElementById("part3fb").innerHTML=document.getElementById("part3fb_en").value ;
	document.getElementById("part4fb").innerHTML=document.getElementById("part4fb_en").value ;
	document.getElementById("part5fb").innerHTML=document.getElementById("part5fb_en").value ;
	document.getElementById("part6fb").innerHTML=document.getElementById("part6fb_en").value ;
	document.getElementById("part7fb").innerHTML=document.getElementById("part7fb_en").value ;
	document.getElementById("part71fb").innerHTML=document.getElementById("part71fb_en").value ;
	document.getElementById("part72fb").innerHTML=document.getElementById("part72fb_en").value ;
	}
	function table1() {
	document.getElementById("age1").innerHTML=document.getElementById("age").innerHTML ;
	document.getElementById("education1").innerHTML=document.getElementById("education").innerHTML ;
	document.getElementById("job1").innerHTML=document.getElementById("job").innerHTML ;
	document.getElementById("hobby1").innerHTML=document.getElementById("hobby").innerHTML ;
	document.getElementById("tol1").innerHTML=document.getElementById("tol").innerHTML ;
	document.getElementById("part2fb1").innerHTML=document.getElementById("part2fb").innerHTML ;
	document.getElementById("part3fb1").innerHTML=document.getElementById("part3fb").innerHTML ;
	document.getElementById("part4fb1").innerHTML=document.getElementById("part4fb").innerHTML ;
	document.getElementById("part5fb1").innerHTML=document.getElementById("part5fb").innerHTML ;
	document.getElementById("part6fb1").innerHTML=document.getElementById("part6fb").innerHTML ;
	document.getElementById("part7fb1").innerHTML=document.getElementById("part7fb").innerHTML ;
	document.getElementById("part71fb1").innerHTML=document.getElementById("part71fb").innerHTML;
	document.getElementById("part72fb1").innerHTML=document.getElementById("part72fb").innerHTML ;
	}
$(document).ready(function(){
	$("#next_1_english").click(function(){
	    if(required("#age_en") && required("#education_en") && required("#job_en") && required("#hobby_en") && required("#tol_en"))
    {
	    $(".part1_en").hide();
	    $(".part2_en").show();
	}
    });
    $("#next_2_english").click(function(){
        if(required("#part2fb_en"))
	{
        $(".part2_en").hide();
	    $(".part3_en").show();
	}
    });
    $("#next_3_english").click(function(){
        if(required("#part3fb_en"))
	{
        $(".part3_en").hide();
	    $(".part4_en").show();
	}
    });
    $("#next_4_english").click(function(){
	    if(required("#part4fb_en"))
	{
		$(".part4_en").hide();
		$(".part5_en").show();
	}
    });
    $("#next_5_english").click(function(){
	    if(required("#part5fb_en"))
	{
        $(".part5_en").hide();
	    $(".part6_en").show();
	}
    });
    $("#next_6_english").click(function(){
	    if(required("#part6fb_en"))
	{
        $(".part6_en").hide();
	    $(".part7_en").show();
	}
    });
    $("#submit_english").click(function(){
	    if(required("#part7fb_en") && required("#part71fb_en") && required("#part72fb_en"))
	{
        $(".part7_en").hide();
	    $(".headingen").hide();
	    $(".part8_en").show();
		table();
	}
    });
    $("#next_1_suomi").click(function(){
	    if(required("#age_suo") && required("#education_suo") && required("#job_suo") && required("#hobby_suo") && required("#tol_suo"))
	{
		document.getElementById("age_en").value = document.getElementById("age_suo").value;
		document.getElementById("education_en").value = document.getElementById("education_suo").value;
		document.getElementById("job_en").value = document.getElementById("job_suo").value;
		document.getElementById("hobby_en").value = document.getElementById("hobby_suo").value;
		document.getElementById("tol_en").value = document.getElementById("tol_suo").value;
		$(".suo").hide();
		$(".en").show();
		$(".part2_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#next_2_suomi").click(function(){
	    if(required("#part2fb_suo"))
	{
		document.getElementById("part2fb_en").value = document.getElementById("part2fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part3_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part2_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#next_3_suomi").click(function(){
	    if(required("#part3fb_suo"))
	{
		document.getElementById("part3fb_en").value = document.getElementById("part3fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part4_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part2_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#next_4_suomi").click(function(){
	    if(required("#part4fb_suo"))
	{
		document.getElementById("part4fb_en").value = document.getElementById("part4fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part5_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part2_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#next_5_suomi").click(function(){
	    if(required("#part5fb_suo"))
	{
		document.getElementById("part5fb_en").value = document.getElementById("part5fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part6_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part2_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#next_6_suomi").click(function(){
	    if(required("#part6fb_suo"))
	{
		document.getElementById("part6fb_en").value = document.getElementById("part6fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part7_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part2_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	}
    });
    $("#submit_suomi").click(function(){
	    if(required("#part7fb_suo") && required("#part71fb_suo") && required("#part72fb_suo"))
	{
		document.getElementById("part7fb_en").value = document.getElementById("part7fb_suo").value;
		document.getElementById("part71fb_en").value = document.getElementById("part71fb_suo").value;
		document.getElementById("part72fb_en").value = document.getElementById("part72fb_suo").value;
        $(".suo").hide();
		$(".en").show();
		$(".part8_en").show();
		$(".headingen").hide();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part2_en").hide();
		$(".finish").hide();
		table();
	}
    });
	$("#translate_1_english").click(function(){
		$(".part1_en").hide();
		$(".headingen").hide();
		$(".part1_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_2_english").click(function(){
		$(".part2_en").hide();
		$(".headingen").hide();
		$(".part2_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part1_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_3_english").click(function(){
		$(".part3_en").hide();
		$(".headingen").hide();
		$(".part3_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part1_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_4_english").click(function(){
		$(".part4_en").hide();
		$(".headingen").hide();
		$(".part4_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part1_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_5_english").click(function(){
		$(".part5_en").hide();
		$(".headingen").hide();
		$(".part5_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part1_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_6_english").click(function(){
		$(".part6_en").hide();
		$(".headingen").hide();
		$(".part6_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part1_suo").hide();
		$(".part7_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_7_english").click(function(){
		$(".part7_en").hide();
		$(".headingen").hide();
		$(".part7_suo").show();
		$(".suo").show();
		$(".headingsuo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part1_suo").hide();
		$(".part8_suo").hide();
		$(".finish").hide();
		$(".finish1").show();
	});
	$("#translate_8_english").click(function(){
		$(".part8_en").hide();
		$(".headingen").hide();
		$(".suo").show();
		$(".part8_suo").show();
		$(".part2_suo").hide();
		$(".part3_suo").hide();
		$(".part4_suo").hide();
		$(".part5_suo").hide();
		$(".part6_suo").hide();
		$(".part7_suo").hide();
		$(".part1_suo").hide();
		$(".headingsuo").hide();
		$(".finish").hide();
		$(".finish1").hide();
		table1();
	});
	$("#translate_1_suomi").click(function(){
		$(".part1_suo").hide();
		$(".headingsuo").hide();
		$(".part1_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_2_suomi").click(function(){
		$(".part2_suo").hide();
		$(".headingsuo").hide();
		$(".part2_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_3_suomi").click(function(){
		$(".part3_suo").hide();
		$(".headingsuo").hide();
		$(".part3_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part1_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_4_suomi").click(function(){
		$(".part4_suo").hide();
		$(".headingsuo").hide();
		$(".part4_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part1_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_5_suomi").click(function(){
		$(".part5_suo").hide();
		$(".headingsuo").hide();
		$(".part5_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part1_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_6_suomi").click(function(){
		$(".part6_suo").hide();
		$(".headingsuo").hide();
		$(".part6_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part1_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_7_suomi").click(function(){
		$(".part7_suo").hide();
		$(".headingsuo").hide();
		$(".part7_en").show();
		$(".en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part1_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
	});
	$("#translate_8_suomi").click(function(){
		$(".part8_suo").hide();
		$(".headingsuo").hide();
		$(".part8_en").show();
		$(".en").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part1_en").hide();
		$(".finish").hide();
		$(".finish1").hide();
	});
	$("#home").click(function(){
	    $(".suo").hide();
	    $(".en").show();
		$(".headingen").show();
		$(".part1_en").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".page1").hide();
		$(".page2").hide();
		$(".page3").hide();
		$(".finish").show();
    });
	$("#return_1_english").click(function(){
	    $(".part2_en").hide();
	    $(".part1_en").show();
		$(".finish").show();
    });
    $("#return_2_english").click(function(){
	    $(".part3_en").hide();
	    $(".part2_en").show();
		$(".finish").show();
    });
    $("#return_3_english").click(function(){
	    $(".part4_en").hide();
	    $(".part3_en").show();
		$(".finish").show();

    });
    $("#return_4_english").click(function(){
	    $(".part5_en").hide();
	    $(".part4_en").show();
		$(".finish").show();
    });
    $("#return_5_english").click(function(){
	    $(".part6_en").hide();
	    $(".part5_en").show();
		$(".finish").show();
    });
    $("#return_6_english").click(function(){
	    $(".part7_en").hide();
	    $(".part6_en").show();
		$(".finish").show();
    });
    $("#return_1_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part1_en").show();
		$(".headingen").show();
		$(".part2_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
    $("#return_2_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part2_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
    $("#return_3_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part3_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part2_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
    $("#return_4_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part4_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part2_en").hide();
		$(".part5_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
    $("#return_5_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part5_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part2_en").hide();
		$(".part6_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
    $("#return_6_suomi").click(function(){
	    $(".suo").hide();
		$(".en").show();
		$(".part6_en").show();
		$(".headingen").show();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part2_en").hide();
		$(".part7_en").hide();
		$(".part8_en").hide();
		$(".finish").show();
		$(".finish1").hide();
    });
	$("#finish_en").click(function(){
		$(".suo").hide();
		$(".en").show();
		$(".part8_en").show();
		$(".headingen").hide();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part2_en").hide();
		$(".part7_en").hide();
		$(".part6_en").hide();
		$(".finish").hide();
		table();
    });
	$("#finish_suo").click(function(){
		$(".suo").hide();
		$(".en").show();
		$(".part8_en").show();
		$(".headingen").hide();
		$(".part1_en").hide();
		$(".part3_en").hide();
		$(".part4_en").hide();
		$(".part5_en").hide();
		$(".part2_en").hide();
		$(".part7_en").hide();
		$(".part6_en").hide();
		$(".finish").hide();
		table();
	});
	$("#slide_down").hover(function() {
	    $(".link1").slideDown(function() {   
		    $(".link2").slideDown(1000);
		    $(".link3").slideDown(1000);
		    $(".close").slideDown(1000);
    });
    });
    $("#close_button").click(function(){
        $(".close").slideUp(function(){
	        $(".link3").slideUp(1000);
		    $(".link2").slideUp(1000);
		    $(".link1").slideUp(1000);
    });
    });
	$("#school").click(function(){
		$(".page1").fadeToggle("slow");
	});
	$("#about").click(function(){
		$(".page2").fadeToggle("slow");
	});
	$("#contact").click(function(){
		$(".page3").fadeToggle("slow");
	});

});