function required(id){
	if($.trim($(id).val())!=""){
		return true;}
	else {
		return false;}
	}
	function table() {
	document.getElementById("age").innerHTML=document.getElementById("age_en").value;
	document.getElementById("education").innerHTML=document.getElementById("education_en").value;
	document.getElementById("job").innerHTML=document.getElementById("job_en").value;
	document.getElementById("hobby").innerHTML=document.getElementById("hobby_en").value;
	document.getElementById("tol").innerHTML=document.getElementById("tol_en").value;
	document.getElementById("part2fb").innerHTML=document.getElementById("part2fb_en").value;
	document.getElementById("part3fb").innerHTML=document.getElementById("part3fb_en").value;
	document.getElementById("part4fb").innerHTML=document.getElementById("part4fb_en").value;
	document.getElementById("part5fb").innerHTML=document.getElementById("part5fb_en").value;
	document.getElementById("part6fb").innerHTML=document.getElementById("part6fb_en").value;
	document.getElementById("part7fb").innerHTML=document.getElementById("part7fb_en").value;
	document.getElementById("part71fb").innerHTML=document.getElementById("part71fb_en").value;
	document.getElementById("part72fb").innerHTML=document.getElementById("part72fb_en").value;
	}
	function table1() {
	document.getElementById("age1").innerHTML=document.getElementById("age_suo").value;
	document.getElementById("education1").innerHTML=document.getElementById("education_suo").value;
	document.getElementById("job1").innerHTML=document.getElementById("job_suo").value;
	document.getElementById("hobby1").innerHTML=document.getElementById("hobby_suo").value;
	document.getElementById("tol1").innerHTML=document.getElementById("tol_suo").value;
	document.getElementById("part2fb1").innerHTML=document.getElementById("part2fb_suo").value;
	document.getElementById("part3fb1").innerHTML=document.getElementById("part3fb_suo").value;
	document.getElementById("part4fb1").innerHTML=document.getElementById("part4fb_suo").value;
	document.getElementById("part5fb1").innerHTML=document.getElementById("part5fb_suo").value;
	document.getElementById("part6fb1").innerHTML=document.getElementById("part6fb_suo").value;
	document.getElementById("part7fb1").innerHTML=document.getElementById("part7fb_suo").value;
	document.getElementById("part71fb1").innerHTML=document.getElementById("part71fb_suo").value;
	document.getElementById("part72fb1").innerHTML=document.getElementById("part72fb_suo").value;
	}
$(document).ready(function(){
    $("#english").click(function(){
        $(".suo").hide();
	    $(".headingen").show();
	    $(".part1_en").show();
	    $(".en").show();
	    $(".part2_en").hide();
	    $(".part3_en").hide();
	    $(".part4_en").hide();
	    $(".part5_en").hide();
	    $(".part6_en").hide();
	    $(".part7_en").hide();
	    $(".part8_en").hide();
    });
	
	$("#next_1_english").click(function(){
	    if(required("#age_en") && required("#education_en") && required("#job_en") && required("#hobby_en") && required("#tol_en"))
    {
	    $(".part1_en").hide();
	    $(".part2_en").show();
	}
    });
    $("#next_2_english").click(function(){
        if(required("#part2fb_en"))
	{
        $(".part2_en").hide();
	    $(".part3_en").show();
	}
    });
    $("#next_3_english").click(function(){
        if(required("#part3fb_en"))
	{
        $(".part3_en").hide();
	    $(".part4_en").show();
	}
    });
    $("#next_4_english").click(function(){
	    if(required("#part4fb_en"))
	{
    $(".part4_en").hide();
	$(".part5_en").show();
	}
    });
    $("#next_5_english").click(function(){
	    if(required("#part5fb_en"))
	{
        $(".part5_en").hide();
	    $(".part6_en").show();
	}
    });
    $("#next_6_english").click(function(){
	    if(required("#part6fb_en"))
	{
        $(".part6_en").hide();
	    $(".part7_en").show();
	}
    });
    $("#submit_english").click(function(){
	    if(required("#part7fb_en") && required("#part71fb_en") && required("#part72fb_en"))
	{
        $(".part7_en").hide();
	    $(".headingen").hide();
	    $(".part8_en").show();
		table();
	}
    });
	$("#suomi").click(function(){
        $(".en").hide();
	    $(".suo").show();
	    $(".part1_suo").show();
	    $(".headingsuo").show();
	    $(".part2_suo").hide();
	    $(".part3_suo").hide();
	    $(".part4_suo").hide();
	    $(".part5_suo").hide();
	    $(".part6_suo").hide();
	    $(".part7_suo").hide();
	    $(".part8_suo").hide();
    });
    $("#next_1_suomi").click(function(){
	    if(required("#age_suo") && required("#education_suo") && required("#job_suo") && required("#hobby_suo") && required("#tol_suo"))
	{
        $(".part1_suo").hide();
	    $(".part2_suo").show();
	}
    });
    $("#next_2_suomi").click(function(){
	    if(required("#part2fb_suo"))
	{
        $(".part2_suo").hide();
	    $(".part3_suo").show();
	}
    });
    $("#next_3_suomi").click(function(){
	    if(required("#part3fb_suo"))
	{
        $(".part3_suo").hide();
	    $(".part4_suo").show();
	}
    });
    $("#next_4_suomi").click(function(){
	    if(required("#part4fb_suo"))
	{
        $(".part4_suo").hide();
	    $(".part5_suo").show();
	}
    });
    $("#next_5_suomi").click(function(){
	    if(required("#part5fb_suo"))
	{
        $(".part5_suo").hide();
	    $(".part6_suo").show();
	}
    });
    $("#next_6_suomi").click(function(){
	    if(required("#part6fb_suo"))
	{
        $(".part6_suo").hide();
	    $(".part7_suo").show();
	}
    });
    $("#submit_suomi").click(function(){
	    if(required("#part7fb_suo") && required("#part71fb_suo") && required("#part72fb_suo"))
	{
        $(".part7_suo").hide();
	    $(".headingsuo").hide();
	    $(".part8_suo").show();
		table1();
	}
    });
});